import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {GlobalStateProvider} from "@/app/privoders/global-state";
import {rangeArray} from "@/app/lib/helper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalState = {
    years: rangeArray(2024, 2104),
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStateProvider globalState={globalState}>
          {children}
        </GlobalStateProvider>
      </body>
    </html>
  );
}
